def more_info():
    print("Beverage: Beverages refer to any liquid that you can drink.\n"
          " They come in various forms, including soft drinks, juices,\n"
          " coffee, tea, and even alcoholic drinks like beer and wine.\n"
          " These are typically consumed for refreshment or hydration.\n\n"
          "Cleaners: Cleaners are household products used for \n"
          " cleaning and maintaining hygiene. They include items like dishwashing\n"
          " liquid, surface cleaners, laundry detergent, and disinfectants. \n"
          " Keeping things spick and span! \n"
          "Personal Care: Personal care products are all about self-care. They\n"
          " include toiletries like shampoo, soap, toothpaste, and skincare\n"
          " items. Taking care of yourself is essential, whether it’s a relaxing\n"
          " bath or brushing your teeth before bed.\n\n"
          "Canned: Canned goods are food items preserved in metal containers.\n"
          " They have a long shelf life and are convenient for storage. \n"
          " Examples include canned vegetables, soups, and fruits. Just be\n"
          " mindful of sodium content in some canned products.\n\n" 
          "Dairy: Dairy products come from milk. They include items like cheese,\n"
          " yogurt, butter, and milk itself. Dairy provides essential nutrients \n"
          " like calcium and protein. Plus, it’s a staple in \n"
          " many cuisines around the world.\n\n"
          "Junk Foods: Junk foods are tasty but often less nutritious\n"
          " snacks. They’re usually high in calories, sugar, salt, and\n"
          " unhealthy fats. Think of potato chips, candy bars, and sugary \n"
          " sodas. While they’re enjoyable as occasional treats, it’s essential\n"
          " to balance them with healthier options.\n\n"
          "Seasonings: Seasonings are flavor enhancers used to make food more \n"
          " delicious. They include herbs, spices, and condiments. Think of \n"
          " salt, pepper, garlic powder, cinnamon, and oregano. They add \n"
          " depth and character to your dishes.\n\n")